### ISSUE TITLE
Invocation failed with minimal example

### ISSUE THREAD

**Issue by maxnatamo** [devlooped/moq#1289]
I've tried looking through the existing issues, but I wasn't able to find anything useful.
The example below uses Moq 4.18.2.

Using Strict-mode, this setup fails to execute:
```cs
public interface ITest
    {
        public Guid GetRandomGuid();

        public string GetRandomGuidString();
    }

    public class Test : ITest
    {
        public Guid GetRandomGuid()
        {
            return Guid.NewGuid();
        }

        public string GetRandomGuidString()
        {
            return GetRandomGuid().ToString();
        }
    }

    public class TestSuite
    {
        [Fact]
        public void TestGuid()
        {
            // Arrange
            var mock = new Mock<ITest>(MockBehavior.Strict);

            mock.Setup(v => v.GetRandomGuid()).Returns(Guid.Empty);

            // Act
            string guid = mock.Object.GetRandomGuidString();

            // Assert
            guid.Should().BeEquivalentTo(Guid.Empty.ToString());
        }
    }
```

This mimics a very simple setup, however, it stops us from creating unit tests.

```
[xUnit.net 00:00:01.99]     moq_issue.TestSuite.TestGuid [FAIL]
  Failed moq_issue.TestSuite.TestGuid [95 ms]
  Error Message:
   Moq.MockException : ITest.GetRandomGuidString() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
  Stack Trace:
     at Moq.FailForStrictMock.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\src\Moq\Interception\InterceptionAspects.cs:line 182
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\src\Moq\Interception\Mock.cs:line 27
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in C:\projects\moq4\src\Moq\Interception\CastleProxyFactory.cs:line 107
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ITestProxy.GetRandomGuidString()
   at moq_issue.TestSuite.TestGuid() in C:\Projects\sandbox\moq-issue\Program.cs:line 38
```

**Comment by stakx** [comment]
You're calling `GetRandomGuidString` on an `ITest` mock, but you haven't set that method up, so the strict mock throws, which is the correct and expected behavior.

Your `Test` class (which implements `ITest`) isn't used in your unit test at all. The fact that you've included it above makes me suspect that you may have been misled by it.
