### ISSUE TITLE
Moq dependency uprev is not working as expected

### ISSUE THREAD

**Issue by mhnir** [devlooped/moq#1432]
## Describe the Bug
Moq has a dependency hierarchy as follows
 System.Threading.Tasks.Extensions >= 4.5.4
     System.Runtime.CompilerServices.Unsafe >= 4.5.3

In my application I use
System.Runtime.CompilerServices.Unsafe to 4.7.0

so from the Moq definition, everything is fine..

But trying to execute a unit test that uses AsSpan() from System.Memory
throws an exception (during Release and Debug mode)

System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=System.Memory
  StackTrace:
   at System.MemoryExtensions.AsSpan(String text)
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\source\repos\ConsoleApp9\UnitTestProject1\UnitTest1.cs:line 13

## Steps to Reproduce

Create a unit test project with the following nugets:

Moq Version="4.20.69" 
MSTest.TestAdapter Version="2.2.8" 
MSTest.TestFramework Version="2.2.8" 
System.Memory Version="4.5.4"
System.Runtime.CompilerServices.Unsafe Version="4.7.0"

Try to run (release or debug) and you'll get an exception on the b = a.AsSpan() line.

```c#
namespace UnitTestProject1
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            string a = "asdfdsa";
            var b = a.AsSpan();
        }
    }
}
```

## Expected Behavior

following the dependency definition, Moq should work with System.Runtime.CompilerServices.Unsafe 4.7.0

## Exception with Stack Trace

```text
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=System.Memory
  StackTrace:
   at System.MemoryExtensions.AsSpan(String text)
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\source\repos\ConsoleApp9\UnitTestProject1\UnitTest1.cs:line 13

```

## Version Info
Target Framework is net4.6.2.
Using SDK csproj

Referenced packages:
Moq Version="4.20.69" 
MSTest.TestAdapter Version="2.2.8" 
MSTest.TestFramework Version="2.2.8" 
System.Memory Version="4.5.4"
System.Runtime.CompilerServices.Unsafe Version="4.7.0"

## Additional Info

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Sounds like you'd need a binding redirect for that assembly
